"""agentkit.topology.config — the config file + the code emitter.

Tool 1 output: `build_config(spec)` runs select+generate and packages the result
into a `TopologyConfig` that serializes to JSON (stdlib, no YAML dep) — the
configuration file the user asked for.

Tool 2: `emit_topologies_py(config)` turns that config into a Python module in
the SAME shape as `lab-04-6-durable-runtime/src/topologies.py` — a builder
function returning `(dag, concurrency)`.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from pathlib import Path

from agentkit.topology.core import (
    TaskSpec,
    TopologyChoice,
    generate_dag,
    select_topology,
)

DEFAULT_MODEL = "gemma-4-26B-A4B-it-heretic-4bit"


@dataclass(frozen=True)
class TopologyConfig:
    """Everything needed to reproduce a run: the task spec, the rule verdict, and
    the generated DAG. This is the serialized artifact (Tool 1's output)."""

    spec: TaskSpec
    choice: TopologyChoice
    dag: dict
    concurrency: int
    model: str = DEFAULT_MODEL
    llm: bool = True


def build_config(
    spec: TaskSpec, *, llm: bool = True, model: str = DEFAULT_MODEL,
    sleep_s: float = 0.1,
) -> TopologyConfig:
    """Run the rules (select) + DAG generation → a serializable config."""
    choice = select_topology(spec)
    dag, concurrency = generate_dag(choice, spec, llm=llm, model=model, sleep_s=sleep_s)
    return TopologyConfig(spec=spec, choice=choice, dag=dag,
                          concurrency=concurrency, model=model, llm=llm)


# -- JSON I/O ---------------------------------------------------------------

def to_json(config: TopologyConfig, indent: int = 2) -> str:
    return json.dumps(asdict(config), indent=indent)


def from_json(text: str) -> TopologyConfig:
    d = json.loads(text)
    # JSON has no tuples — coerce the tuple-typed fields back so the round-trip
    # is type-faithful (downstream may rely on immutability / tuple identity).
    spec_d = dict(d["spec"])
    spec_d["subtasks"] = tuple(spec_d.get("subtasks", ()))
    choice_d = dict(d["choice"])
    choice_d["questions_fired"] = tuple(choice_d.get("questions_fired", ()))
    return TopologyConfig(
        spec=TaskSpec(**spec_d),
        choice=TopologyChoice(**choice_d),
        dag=d["dag"],
        concurrency=d["concurrency"],
        model=d.get("model", DEFAULT_MODEL),
        llm=d.get("llm", True),
    )


def write_config(path: str | Path, config: TopologyConfig) -> None:
    Path(path).write_text(to_json(config), encoding="utf-8")


def load_config(path: str | Path) -> TopologyConfig:
    return from_json(Path(path).read_text(encoding="utf-8"))


# -- Tool 2: code emitter (config → topologies.py-style module) -------------

def emit_topologies_py(config: TopologyConfig) -> str:
    """Emit a Python module mirroring `topologies.py`: a `build()` function
    returning `(dag, concurrency)`. The DAG is rendered as a literal (the runtime
    `{"nodes","edges"}` shape contains only str/list/dict — valid Python *and*
    JSON, so `json.dumps` is a safe code literal)."""
    c = config.choice
    fired = ", ".join(c.questions_fired)
    # Re-indent the literal so it reads as a function-body assignment.
    dag_body = json.dumps(config.dag, indent=4).replace("\n", "\n    ")
    return f'''"""Generated by agentkit.topology — {c.topology} topology.

Task: {config.spec.task}
Rule fired ({fired}): {c.rationale}
Trigger: {c.trigger}

Mirrors lab-04-6-durable-runtime/src/topologies.py: a builder returning
(dag, concurrency). Feed the dag to agentkit.runtime GraphStore.create_graph.
"""
from __future__ import annotations

from typing import Any

TOPOLOGY = "{c.topology}"
TRIGGER = "{c.trigger}"
MODEL = "{config.model}"


def build() -> tuple[dict[str, Any], int]:
    """{c.rationale}"""
    dag = {dag_body}
    return dag, {config.concurrency}
'''


def write_topologies_py(path: str | Path, config: TopologyConfig) -> None:
    Path(path).write_text(emit_topologies_py(config), encoding="utf-8")


def _demo() -> None:
    """Self-check: round-trip JSON, and the emitted code is importable + matches."""
    import tempfile
    import types

    spec = TaskSpec("review PR", subtasks=("security", "tests", "perf"),
                    subtasks_independent=True)
    cfg = build_config(spec, llm=False)
    assert cfg.choice.topology == "star" and cfg.concurrency == 3

    # JSON round-trip is lossless.
    rt = from_json(to_json(cfg))
    assert rt.dag == cfg.dag and rt.choice.topology == cfg.choice.topology
    assert rt.spec.subtasks == ("security", "tests", "perf")

    # Emitted module executes and yields the same dag + concurrency.
    src = emit_topologies_py(cfg)
    mod = types.ModuleType("gen_topo")
    exec(compile(src, "<gen_topo>", "exec"), mod.__dict__)  # noqa: S102 — codegen self-test
    dag, conc = mod.build()
    assert dag == cfg.dag and conc == cfg.concurrency
    assert mod.TOPOLOGY == "star"
    with tempfile.TemporaryDirectory() as d:
        p = Path(d) / "topo.json"
        write_config(p, cfg)
        assert load_config(p).dag == cfg.dag
    print("topology.config._demo OK")


if __name__ == "__main__":
    _demo()
